name: jobsity_challenge
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"
  
dependencies:
  flutter:
      sdk: flutter
  animations: ^2.0.3
  beamer: ^1.5.0
  bloc: ^8.0.3
  cached_network_image: ^3.2.1
  collection: ^1.16.0
  dartz: ^0.10.1
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.0
  dio_cache_interceptor_hive_store: ^3.2.0
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.1.0
  hive: ^2.2.3
  path_provider: ^2.0.11
  simple_html_css: ^4.0.0
  local_auth: ^2.1.1
  flutter_screen_lock: ^7.0.4
  crypto: ^3.0.2
  mocktail: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1


flutter:
  uses-material-design: true
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/poppins/Poppins-Thin.ttf
        weight: 100
      - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/poppins/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/poppins/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/poppins/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/poppins/Poppins-Semibold.ttf
        weight: 600
      - asset: assets/fonts/poppins/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/poppins/Poppins-Black.ttf
        weight: 900